name: Frontend Continuous Integration

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  NODE_VERSION: 18.18.0
  IMAGE_REPO_NAME: frontend

jobs:
  lint:
    name: LINT JOB
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
      - name: Perform a cache action to restore cache before dependency install
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-cache-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: |
           npm ci
           npm install eslint --save-dev
      - name: Run lint
        run: npm run lint
          
  test:
    name: TEST JOB
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
      - name: Perform a cache action to restore cache before dependency install
        id: cache-npm-test
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-cache-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: |
          npm ci
          npm install prettier --save-dev
      - name: Run test
        run: npm run test

  build:
    name: BUILD JOB
    needs: [lint, test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Perform a cache action to restore cache before dependency install
        id: cache-npm-build
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-cache-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: |
          npm ci
          npm install prettier --save-dev

      - name: Run test
        run: npm run test
        
      - name: Docker Build
        run: |
          docker build -t ${{env.IMAGE_REPO_NAME}}:latest .
